Client/SIGECO-Norte.Web/Areas/Comision/Controllers/GestionComisionManualController.cs
using Newtonsoft.Json;
using SIGEES.BusinessLogic;
using SIGEES.Entidades;
using SIGEES.Web.Areas.Comision.Models;
using SIGEES.Web.Areas.Comision.Services;
using SIGEES.Web.MemberShip.Filters;
using SIGEES.Web.Models;
using SIGEES.Web.Models.Bean;
using SIGEES.Web.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SIGEES.Web.Areas.Comision.Controllers
{
    public class GestionComisionManualController : Controller
    {
        private BeanSesionUsuario beanSesionUsuario = new BeanSesionUsuario();
        private readonly ITipoAccesoItemService _tipoAccesoItemService;
        private readonly IParametroSistemaService _IParametroSistemaService;
        //private readonly EventoUsuarioService _eventoUsuarioService;

        private readonly TipoPagoService _tipoPagoService;
        private readonly EmpresaSIGECOService _empresaService;
        private readonly CanalGrupoService _canalService;

        //protected override void Initialize(System.Web.Routing.RequestContext requestContext)
        //{
        //    base.Initialize(requestContext);
        //    beanSesionUsuario = Session[Common.Constante.session_name.sesionUsuario] as BeanSesionUsuario;
        //}
        public GestionComisionManualController()
        {
            _IParametroSistemaService = new ParametroSistemaService();
            _tipoAccesoItemService = new TipoAccesoItemService();
            _tipoPagoService = new TipoPagoService();
            _empresaService = new EmpresaSIGECOService();
            _canalService = new CanalGrupoService();
        }

        public ActionResult GetTipoPagoJson()
        {
            string result = this._tipoPagoService.GetAllComboJson();
            return Content(result, "application/json");
        }

        public ActionResult GetEmpresaJson()
        {
            string result = this._empresaService.GetAllComboJson();
            return Content(result, "application/json");
        }

        public ActionResult GetCanalJson()
        {
            string result = this._canalService.GetCanalAllComboJson();
            return Content(result, "application/json");
        }

        
        public ActionResult ValidarReferencia(string codigo_comision_manual)
        {
            string result = ComisionManualBL.Instance.ValidarReferencia(Convert.ToInt32(codigo_comision_manual));
            return Content(JsonConvert.SerializeObject(new { mensaje = result}), "application/json");
        }

        [RequiresAuthentication]
        public ActionResult Index()
        {
            BeanItemTipoAcceso bean = new BeanItemTipoAcceso();
            try
            {
                beanSesionUsuario = Session[Common.Constante.session_name.sesionUsuario] as BeanSesionUsuario;
                bean = _tipoAccesoItemService.GetBeanItemTipoAcceso(beanSesionUsuario.codigoPerfil);
            }
            catch (Exception ex)
            {

                ex.ToString();
            }


            return View(bean);
        }

        [HttpGet]
        [RequiresAuthentication]
        public ActionResult _Registrar(int p_codigo_comision)
        {
            comision_manual_dto v_entidad = new comision_manual_dto();
            try
            {
                parametro_sistema v_parametro;

                if (p_codigo_comision < 0)
                {
                    v_parametro = _IParametroSistemaService.GetParametro((int)SIGEES.Web.Areas.Comision.Utils.Parametro.comision_manual_tipo_venta);
                    v_entidad.nombre_tipo_venta = v_parametro.valor.Split(Convert.ToChar("|"))[1];
                    v_entidad.codigo_tipo_venta = Convert.ToInt32(v_parametro.valor.Split(Convert.ToChar("|"))[0]);
                    v_parametro = _IParametroSistemaService.GetParametro((int)SIGEES.Web.Areas.Comision.Utils.Parametro.comision_manual_tipo_pago);
                    v_entidad.nombre_tipo_pago = v_parametro.valor.Split(Convert.ToChar("|"))[1];
                    v_entidad.codigo_tipo_pago = Convert.ToInt32(v_parametro.valor.Split(Convert.ToChar("|"))[0]);
                    
                }
                else 
                {
                    v_entidad = ComisionManualBL.Instance.Detalle(p_codigo_comision);
                }
                
               v_parametro = _IParametroSistemaService.GetParametro((int)SIGEES.Web.Areas.Comision.Utils.Parametro.igv);
                v_entidad.igv = decimal.Parse(v_parametro.valor);
            }
            catch (Exception  ex)
            {

                string m = ex.Message;
            }

            return PartialView(v_entidad);
        }

        [HttpGet]
        [RequiresAuthentication]
        public ActionResult _Detalle(int p_codigo_comision)
        {
            comision_manual_dto v_entidad = new comision_manual_dto();
            try
            {
                parametro_sistema v_parametro;
                v_entidad = ComisionManualBL.Instance.Detalle(p_codigo_comision);

                v_parametro = _IParametroSistemaService.GetParametro((int)SIGEES.Web.Areas.Comision.Utils.Parametro.igv);
                v_entidad.igv = decimal.Parse(v_parametro.valor);
            }
            catch (Exception ex)
            {

                string m = ex.Message;
            }

            return PartialView(v_entidad);
        }

        [HttpGet]
        [RequiresAuthentication]
        public ActionResult _Modificar(int p_codigo_comision)
        {
            comision_manual_dto v_entidad = new comision_manual_dto();
            try
            {
                parametro_sistema v_parametro;
                v_entidad = ComisionManualBL.Instance.Detalle(p_codigo_comision);

                v_parametro = _IParametroSistemaService.GetParametro((int)SIGEES.Web.Areas.Comision.Utils.Parametro.igv);
                v_entidad.igv = decimal.Parse(v_parametro.valor);
            }
            catch (Exception ex)
            {

                string m = ex.Message;
            }

            return PartialView(v_entidad);
        }

        [HttpGet]        
        public ActionResult _Busqueda_Articulo()
        {
            //ParametroViewModel vm = new ParametroViewModel();
            //vm.codigo_empresa = p_codigo_empresa;
            //vm.numero_contrato = p_nro_contrato;
            //return PartialView(vm);
            return PartialView();
        }

        [HttpGet]        
        public ActionResult _Busqueda_Personal()
        {            
            return PartialView();
        }

        public ActionResult GetPersonalJson(string nombre)
        {
            var lista = new PersonalBL().ListarParaComisionManual(nombre);
            return Content(JsonConvert.SerializeObject(lista), "application/json");
        }

        [HttpPost]
        
        public ActionResult GetListarArticuloJson(string codigo_empresa, string nro_contrato, string nombre, string codigo_personal, string codigo_canal, string codigo_tipo_venta, string codigo_tipo_pago)
        {
            var lista = new List<articulo_comision_manual_listado_dto>();
            var busqueda = new articulo_comision_manual_busqueda_dto();
            string v_mensaje = string.Empty;
            int v_operacion = 1;
            int v_total = 0;
            try
            {
                busqueda.codigo_empresa = null;
                //busqueda.nro_contrato = null;

                if (codigo_empresa.Length > 0)
                    busqueda.codigo_empresa = Convert.ToInt32(codigo_empresa);
                if (nro_contrato.Length > 0)
                    busqueda.nro_contrato = nro_contrato;

                busqueda.nombre = nombre;
                busqueda.codigo_personal = Convert.ToInt32(codigo_personal);
                busqueda.codigo_canal = Convert.ToInt32(codigo_canal);
                busqueda.codigo_tipo_venta = Convert.ToInt32(codigo_tipo_venta); 
                busqueda.codigo_tipo_pago = Convert.ToInt32(codigo_tipo_pago);

                lista = ArticuloBL.Instance.ListarParaComisionManual(busqueda);
                v_total = lista.Count;
                if (v_total == 0)
                    throw new Exception("No se encontró artículos segun los filtros establecidos.");
            }
            catch (Exception ex)
            {
                v_mensaje = ex.Message;
                v_operacion = -1;
            }
            //{"total":0,"rows":[],"sucess":false,"message":"error message"}
            return Content(JsonConvert.SerializeObject(new { total = v_total, rows = lista, sucess = v_operacion, message = v_mensaje }), "application/json");

        }

        [HttpPost]
        public ActionResult GetComisionPersonalArticulo(cronograma_pago_filtro p_cronograma_pago_filtro)
        {

            resumen_pago_comision_personal_dto _v_entidad = new resumen_pago_comision_personal_dto();
            string vMensaje = string.Empty;            
            try
            {
                _v_entidad.mensaje_operacion = string.Empty;
                _v_entidad = DetalleCronogramaPagoSelBL.Instance.GetPagoComisionByArticuloPersonal(p_cronograma_pago_filtro);
                _v_entidad.codigo_tipo_operacion = 1;

                if (_v_entidad.total_registro_encontrado>=1)
                {
                    _v_entidad.mensaje_operacion = "Total de registros encontrados " + _v_entidad.total_registro_encontrado;
                }
                if (_v_entidad.total_registro_encontrado == 0)
                {
                    _v_entidad.mensaje_operacion = "No se encontró comisión personal.";
                }

            }
            catch (Exception ex)
            {            
                _v_entidad.codigo_tipo_operacion = -1;
                _v_entidad.mensaje_operacion = ex.Message;
            }
            return Content(JsonConvert.SerializeObject(_v_entidad), "application/json");
            

        }

        [HttpPost]

Client/SIGECO-Norte.Web/Areas/Comision/Views/GestionComisionManual/Index.cshtml
@model SIGEES.Web.Models.Bean.BeanItemTipoAcceso
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<input type="hidden" id="hdCodigo" value="" />
<input type="hidden" id="hdCodigoPersonal" value="" />
<input type="hidden" id="hdCodigoCanal" value="" />
<input type="hidden" id="hdNroContrato" value="" />
<input type="hidden" id="hdCodigoEmpresa" value="" />
<input type="hidden" id="hdCodigoTipoVenta" value="" />
<input type="hidden" id="hdCodigoTipoPago" value="" />
<input type="hidden" id="hdCodigoCamposanto" value="" />
<input type="hidden" id="hdCodigoArticulo" value="" />
<input type="hidden" id="hdIGV" value="" />

<div style="width: 99%; background-color: #D3EBDE; vertical-align: middle; padding-top: 2%; padding-bottom: 2%; padding-left: 1%">

    <center>
        <h2>Mantenimiento de Comisión Manual</h2>
    </center>
    <div class="panelGridModal">
        <div class="easyui-panel" title="" style="width: 99%; background-color: #D3EBDE; border-color: #D3EBDE;">
            <form id="frm_consultar" method="post">
                <div class="rowGridModal" style="width: 10%;">
                    <label class="colGridModal">Empresa</label>
                </div>
                <div class="rowGridModal" style="width: 15%;">
                    <input class="easyui-combobox" id="cmb_empresa_f" value="0" style="width: 100%" data-options="editable:false,required:false,novalidate:true,validType:'restricted[\'#cmb_empresa_f\']'" />
                </div>
                <div class="rowGridModal" style="width: 10%;">
                    <label class="colGridModal">Canal</label>
                </div>
                <div class="rowGridModal" style="width:15%;">
                    <input class="easyui-combobox" id="cmb_canal" value="0" style="width: 100%" data-options="editable:false,required:false,novalidate:true,panelWidth:300,validType:'restricted[\'#cmb_canal\']'" />
                </div>
                <div class="rowBoth"></div>
                <div class="rowGridModalDouble" style="width: 10%; ">
                    <label class="colGridModal">Registrado</label>
                </div>
                <div class="rowGridModalDouble" style="width:15%;">
                    <input class="easyui-datebox" id="fecha_inicio" value="" style="width: 100%" data-options="required:false,novalidate:true, validType:'fechaMenorIgualA[\'#fecha_fin\',\'Fecha Fin\',\'dd/MM/yyyy\',\'Por favor, ingrese una fecha v&aacute;lida\']'" />
                </div>
                <div class="rowGridModalDouble" style="width: 10%; ">
                    <label class="colGridModal">Hasta</label>
                </div>
                <div class="rowGridModalDouble" style="width:15%;">
                    <input class="easyui-datebox" id="fecha_fin" value="" style="width: 100%" data-options="required:false,novalidate:true" />
                </div>
                <div class="rowGridModal" style="width: 10%;">
                    <label class="colGridModal">Estado</label>
                </div>
                <div class="rowGridModal" style="width: 15%;">
                    <input class="easyui-combobox" id="cmb_estado" style="width: 100%" data-options="editable:false,required:false,novalidate:true,validType:'restricted[\'#cmb_estado\']'" />
                </div>

            </form>
        </div>
        <div class="easyui-panel" title="" style="width: 99%; background-color: #D3EBDE; border-color: #D3EBDE;">
            @if (Model.estadoLectura != null && Model.estadoLectura.CompareTo("A") == 0)
            {
                <a href="javascript:fnBuscar()" id="btnBuscar" class="easyui-linkbutton" style="padding: 2px 15px 2px 15px; " data-options="iconCls:'icon-search'">Buscar</a>
                <a href="javascript:fnDetalle()" id="btnBuscar" class="easyui-linkbutton" style="padding: 2px 15px 2px 15px; " data-options="iconCls:'icon-detail'">Detalle</a>
            }
            @if (Model.estadoComisionManualEscritura != null && Model.estadoComisionManualEscritura.CompareTo("A") == 0)
            {
                <a href="javascript:fnNuevoRegistro();" id="btnNuevo" class="easyui-linkbutton" style="padding: 2px 15px 2px 15px; " data-options="iconCls:'icon-add'">Crear</a>
                <a href="javascript:fnModificar()" id="btnModificar" class="easyui-linkbutton" style="padding: 2px 15px 2px 15px; " data-options="iconCls:'icon-edit'">Modificar</a>
                <a href="javascript:fnDesactivar()" id="btnDesactivar" class="easyui-linkbutton" style="padding: 2px 15px 2px 15px; " data-options="iconCls:'icon-cancel'">Desactivar</a>
            }
            @if (Model.estadoLectura != null && Model.estadoLectura.CompareTo("A") == 0)
            {
                <a href="javascript:fnVerReporte();" class="easyui-linkbutton" style="padding: 2px 15px 2px 15px; " data-options="iconCls:'icon-print'">Exportar</a>
            }
        </div>
    </div>
</div>
<br />
<div style="width: 99%; padding-left: 1%">
    @if (Model.estadoLectura != null && Model.estadoLectura.CompareTo("A") == 0)
    {
        <table id="dgv_comision" style="width: 100%"></table>
    }
</div>

<div id="div_registrar_comision" class="easyui-dialog" data-options="resizable:true,modal:true,closed:true"
     style="width: 950px; height: 560px;line-height: 10px;"></div>

<div id="div_detalle_comision" class="easyui-dialog" data-options="resizable:true,modal:true,closed:true"
     style="width: 950px; height: 583px;line-height: 10px;"></div>

<div id="div_modificar_comision" class="easyui-dialog" data-options="resizable:true,modal:true,closed:true"
     style="width: 950px; height: 520px;line-height: 10px;"></div>

<script type="text/javascript" src="~/Areas/Comision/Scripts/Views/Comision/comision.index.js"></script>
<script type="text/javascript">
    $(document).ready(function () {

        var actionUrls =
        {
            _Registrar: '@Url.Action("_Registrar", "GestionComisionManual", new { area = "Comision" })',
            _Detalle: '@Url.Action("_Detalle", "GestionComisionManual", new { area = "Comision" })',
            _Modificar: '@Url.Action("_Modificar", "GestionComisionManual", new { area = "Comision" })',
            ListarAllJson: '@Url.Action("ListarAllJson", "GestionComisionManual", new { area = "Comision" })',
            Desactivar: '@Url.Action("Desactivar", "GestionComisionManual", new { area = "Comision" })',
            SetFiltroGrilla: '@Url.Action("SetFiltroGrilla", "GestionComisionManual", new { area = "Comision" })',
            GetCampoSantoJson: '@Url.Action("GetCampoSantoJson", "GestionComisionManual", new { area = "Comision" })',
            GetEmpresaJson: '@Url.Action("GetEmpresaJson", "GestionComisionManual", new { area = "Comision" })',
            GetCanalJson: '@Url.Action("GetCanalJson", "GestionComisionManual", new { area = "Comision" })',
            ValidarReferencia: '@Url.Action("ValidarReferencia", "GestionComisionManual", new { area = "Comision" })',
        };

        project.index.Initialize(actionUrls);
    });
</script>

Client/SIGECO-Norte.Web/Areas/Comision/Views/GestionComisionManual/_Busqueda_Articulo.cshtml
<div class="easyui-layout" data-options="fit:true">
    <div data-options="region:'south'" style="padding:10px;">
        <div style="height:100%;">
            <label class="colGridModal" style="color:#f56363;">(*) Para seleccionar un artículo haga doble click sobre el registro.</label>
        </div>
    </div>
    <div data-options="region:'center', border:false" style="padding:10px;">
        <table id="dgv_listado_articulo" style="width: 100%; height: 100%;"></table>
    </div>
</div>

<script type="text/javascript" src="~/Areas/Comision/Scripts/Views/Comision/comision.articulo.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        var actionUrls = {
            _GetListarArticuloJson: '@Url.Action("GetListarArticuloJson", "GestionComisionManual", new { area = "Comision" })',
        };
        project.articulo.Initialize(actionUrls);
    });
</script>

Client/SIGECO-Norte.Web/Areas/Comision/Views/GestionComisionManual/_Busqueda_Personal.cshtml
<div class="easyui-layout" data-options="fit:true">
    <div data-options="region:'south'" style="padding: 10px;">
        <div style="height:100%;">
            <label class="colGridModal" style="color:#f56363;">(*) Para seleccionar un vendedor haga doble click sobre el registro.</label>
        </div>
    </div>
    <div data-options="region:'center', border:false" style="padding:10px;">
        <table id="dgv_listado_personal" style="width: 100%; height: 100%;"></table>
    </div>
</div>

<script type="text/javascript" src="~/Areas/Comision/Scripts/Views/Comision/comision.personal.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        var actionUrls = {
            _GetListarPersonalJson: '@Url.Action("GetPersonalJson", "GestionComisionManual", new { area = "comision" })'          
        };
        project.personal.Initialize(actionUrls);
    });
</script>

Client/SIGECO-Norte.Web/Areas/Comision/Views/GestionComisionManual/_Modificar.cshtml
@model SIGEES.Entidades.comision_manual_dto

<div class="easyui-layout" data-options="fit:true">
    <form id="frm_detalle_comision" method="post">
        <div data-options="region:'center', border:false" style="padding:5px;">
            <div class="easyui-panel" title="Datos del Fallecido" style="width:100%; ">
                <div class="panelGridModal">
                    <table style="width:100%">
                        <tr>
                            <td class="tdEtiqueta">
                                <label class="colGridModal">Tipo Documento</label>
                            </td>
                            <td class="tdValor">
                                <input class="easyui-textbox" id="txt_tipo_documento" value="@Model.nombre_tipo_documento" style="width:99%;" data-options="required: true,novalidate:true,disabled:true" />
                            </td>
                            <td class="tdEtiqueta">
                                <label class="colGridModal">Nro. Documento</label>
                            </td>
                            <td class="tdValor">
                                <input class="easyui-textbox textbox" maxlength="12" id="txt_numero_documento" value="@Model.nro_documento" style="width:99%;" data-options="required: true,disabled:true" />
                            </td>
                        </tr>
                        <tr>
                            <td class="tdEtiqueta">
                                <label class="colGridModal">Nombres</label>
                            </td>
                            <td class="tdValor2" colspan="3">
                                <input class="easyui-textbox textbox" value="@Model.nombre_completo_fallecido" id="txt_nombres_fallecido" maxlength="20" style="width:99%;" data-options="required: true,novalidate:true,disabled:true" />
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
            <div class="easyui-panel" title="Datos Venta" style="width: 100%; ">
                <div class="panelGridModal">
                    <table style="width:100%">
                        <tr>
                            <td class="tdEtiqueta">
                                <label class="colGridModal">Vendedor</label>
                            </td>
                            <td class="tdValor">
                                <input class="easyui-textbox" id="txt_apellidos_nombres_personal" value="@Model.nombre_personal" style="width:100%;" data-options="disabled:true" />
                            </td>
                            <td class="tdEtiqueta">
                                <label class="colGridModal">Canal</label>
                            </td>
                            <td class="tdValor">
                                <input class="easyui-textbox" id="txt_nombre_canal" value="@Model.nombre_canal" style="width:99%;" data-options="novalidate:true,disabled:true" />
                            </td>
                        </tr>
                        <tr>
                            <td class="tdEtiqueta">
                                <label class="colGridModal">Empresa</label>
                            </td>
                            <td class="tdValor">
                                <input class="easyui-textbox" id="txt_empresa" value="@Model.nombre_empresa" style="width:100%;" data-options="required: true,novalidate:true,disabled:true" />
                            </td>
                            <td class="tdEtiqueta">
                                <label class="colGridModal">Nro Contrato</label>
                            </td>
                            <td class="tdValor">
                                <input class="easyui-textbox textbox" id="txt_numero_contrato" maxlength="10" value="@Model.nro_contrato" style="width:99%;" data-options="required: false,novalidate:true,disabled:true" />
                            </td>
                        </tr>
                        <tr>
                            <td class="tdEtiqueta">
                                <label class="colGridModal">Tipo Venta</label>
                            </td>
                            <td class="tdValor">
                                <input class="easyui-textbox" id="txt_tipo_pago" value="@Model.nombre_tipo_venta" style="width:100%;" data-options="disabled:true" />
                            </td>
                            <td class="tdEtiqueta">
                                <label class="colGridModal">Tipo Pago</label>
                            </td>
                            <td class="tdValor">
                                <input class="easyui-textbox" id="txt_tipo_pago" value="@Model.nombre_tipo_pago" style="width:100%;" data-options="required:true,novalidate:true,disabled:true" />
                            </td>
                        </tr>
                        <tr>
                            <td class="tdEtiqueta">
                                <label class="colGridModal">Artículo</label>
                            </td>
                            <td class="tdValor">
                                <input class="easyui-textbox" id="txt_nombre_articulo" value="@Model.nombre_articulo" style="width:100%;" data-options="disabled:true" />
                            </td>
                            <td class="tdEtiqueta">
                                <label class="colGridModal">Factura Vendedor</label>
                            </td>
                            <td class="tdValor">
                                <input class="easyui-validatebox textbox" id="txt_nro_factura_vendedor_m" name="txt_nro_factura_vendedor_m" maxlength="20" value="@Model.nro_factura_vendedor" style="width:99%;" data-options="required: false,novalidate:true" />
                            </td>
                        </tr>
                        <tr>
                            <td class="tdEtiqueta" style="vertical-align:top;">
                                <label class="colGridModal">Comentario</label>
                            </td>
                            <td class="tdValor2" colspan="3">
                                <input class="easyui-textbox" id="txt_comentario" value="@Model.comentario" maxlength="250" style="width:100%;height:50px;" data-options="required: true,disabled:true,multiline:true" />
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
            <div class="easyui-panel" title="Comisión del Vendedor" style="width: 100%; ">
                <table style="width:100%">
                    <tr>
                        <td class="tdEtiqueta">
                            <label class="colGridModal">Importe</label>
                        </td>
                        <td class="tdValor">
                            <input class="easyui-numberbox" id="txt_monto_comision" value="@Model.monto_bruto" style="width: 99%; text-align: right;" data-options="required: true,novalidate:true,disabled:true,precision:2,groupSeparator:','" />
                        </td>
                        <td colspan="2">&nbsp;</td>
                    </tr>
                    <tr>
                        <td class="tdEtiqueta">
                            <label class="colGridModal">IGV(@Model.igv)%</label>
                        </td>
                        <td class="tdValor">
                            <input class="easyui-numberbox" id="txt_monto_igv" value="@Model.monto_igv" style="width: 99%; text-align: right;" data-options="required: true,novalidate:true,disabled:true,precision:2,groupSeparator:','" />
                        </td>
                        <td colspan="2">&nbsp;</td>
                    </tr>
                    <tr>
                        <td class="tdEtiqueta">
                            <label class="colGridModal">Total</label>
                        </td>
                        <td class="tdValor">
                            <input class="easyui-numberbox" id="txt_monto_total_comision" value="@Model.monto_neto" style="width:99%; text-align:right;" data-options="required: true,novalidate:true,disabled:true,precision:2,groupSeparator:','" />
                        </td>
                        <td colspan="2">&nbsp;</td>
                    </tr>
                </table>
            </div>
        </div>
        <div data-options="region:'south',border:true" style="text-align:right;padding:5px;height:38px">
            <a href="javascript:GuardarModificar();" class="easyui-linkbutton" style="padding: 0px 10px 0px 10px; " iconcls="icon-save" id="btnGuardar">Guardar</a>
            <a href="javascript:CerrarModificar();" class="easyui-linkbutton" style="padding: 0px 10px 0px 10px; " iconcls="icon-cancel" id="btnCancelar">Cerrar</a>
        </div>
    </form>
</div>
<style>
    .tdEtiqueta {
        width: 15%;
        padding: 10px;
    }

    .tdValor {
        width: 35%;
    }

    .tdValor2 {
        width: 85%;
    }
</style>

<script type="text/javascript" src="~/Areas/Comision/Scripts/Views/Comision/comision.modificar.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        var actionUrls =
        {
            ActualizarLimitado: '@Url.Action("ActualizarLimitado", "GestionComisionManual", new { area = "Comision" })',
            ValidarReferencia: '@Url.Action("ValidarReferencia", "GestionComisionManual", new { area = "Comision" })',
            _codigo_comision_manual: '@Model.codigo_comision_manual'
        };

        project.modificarcomision.Initialize(actionUrls);
    });
</script>