Client/SIGECO-Norte.Web/Areas/Comision/Controllers/ComisionPersonalInactivoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

using SIGEES.BusinessLogic;
using SIGEES.Entidades;

using SIGEES.Web.Areas.Comision.Services;
using SIGEES.Web.Areas.Comision.Utils;

using SIGEES.Web.Core;
using SIGEES.Web.Models;
using SIGEES.Web.Models.Bean;
using SIGEES.Web.Services;
using SIGEES.Web.Utils;

using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using SIGEES.Web.MemberShip.Filters;
using Microsoft.Reporting.WebForms;

namespace SIGEES.Web.Areas.Comision.Controllers
{
    public class ComisionPersonalInactivoController : Controller
    {
        //
        // GET: /Comision/LogContratoSAP/

        private BeanSesionUsuario beanSesionUsuario = new BeanSesionUsuario();
        private readonly ITipoAccesoItemService _tipoAccesoItemService;
        private readonly CanalGrupoService _canalService;

        // private canal_grupo _canal_grupo = null;

        #region Inicializacion de Controller - Menu
        protected override void Initialize(System.Web.Routing.RequestContext requestContext)
        {
            base.Initialize(requestContext);
            beanSesionUsuario = Session[Common.Constante.session_name.sesionUsuario] as BeanSesionUsuario;
        }
        public ComisionPersonalInactivoController()
        {
            _tipoAccesoItemService = new TipoAccesoItemService();
            _canalService = new CanalGrupoService();
        }
        #endregion

        [RequiresAuthentication]
        public ActionResult Index()
        {
            BeanItemTipoAcceso bean = new BeanItemTipoAcceso();
            bean = _tipoAccesoItemService.GetBeanItemTipoAcceso(beanSesionUsuario.codigoPerfil);
            return View(bean);
        }

        [RequiresAuthentication]
        [HttpPost]
        public ActionResult GetAllJson(string fecha_inicio, string fecha_fin, string codigo_canal, string liquidado)
        {
            detalle_cronograma_personal_inactivo_busqueda_dto busqueda = new detalle_cronograma_personal_inactivo_busqueda_dto
            {
                fecha_inicio = fecha_inicio,
                fecha_fin = fecha_fin,
                codigo_canal = codigo_canal,
                liquidado = Convert.ToInt32(liquidado)
            };

            var lista = DetalleCronogramaPagoSelBL.Instance.ListadoComisionPersonalInactivo(busqueda);
            return Content(JsonConvert.SerializeObject(lista), "application/json");
        }

        [HttpGet]
        public ActionResult GetCanalJson()
        {
            string result = this._canalService.GetCanalAllComboJson();
            return Content(result, "application/json");
        }


        [HttpGet]
        public ActionResult GetLiquidadoJson()
        {
            string result = Listados.GetLiquidadoJson(true);
            return Content(result, "application/json");
        }


        public ActionResult GetFechasJson()
        {
            var lista = DetalleCronogramaPagoSelBL.Instance.FechasComisionPersonalInactivo();
            return Content(JsonConvert.SerializeObject(lista), "application/json");
        }

        [HttpPost]
        public ActionResult SetExportData(List<detalle_cronograma_personal_inactivo_dto> listado)
        {
            Guid id = Guid.NewGuid();

            string v_guid = id.ToString().Replace('-', '_');
            Session[v_guid] = listado;

            return Json(new { v_guid = v_guid }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ExportarExcel(string id)
        {
            string FileType = "Excel";
            string ContentType = "application/vnd.ms-excel";

            List<detalle_cronograma_personal_inactivo_dto> lst = new List<detalle_cronograma_personal_inactivo_dto>();
            try
            {
                lst = Session[id] as List<detalle_cronograma_personal_inactivo_dto>;

                ReportDataSource dataSource = new ReportDataSource("dsComision", lst);
                LocalReport rpt = new LocalReport();
                rpt.ReportPath = Server.MapPath("~/Areas/Comision/Reporte/ComisionPersonalInactivo/rdl/rpt_comisionpersonalinactivo.rdlc");

                rpt.DataSources.Clear();
                rpt.DataSources.Add(dataSource);

                string reportType = FileType;
                string mimeType;
                string encoding;
                string fileNameExtension;
                Warning[] warnings;
                string[] streams;
                byte[] renderedBytes = rpt.Render(reportType, null, out mimeType, out encoding, out fileNameExtension, out streams, out warnings);
                return File(renderedBytes, ContentType, "ComisionPersonalInactivo.xls");
            }
            catch (Exception ex)
            {

                string mensaje = ex.Message;
            }
            finally
            {
                Session.Remove(id);
            }
            return null;
        }

        [HttpPost]
        [RequiresAuthentication]
        public ActionResult Aprobar(List<detalle_cronograma_personal_inactivo_dto> lst_detalle, int nivel, int codigo_resultado, string observacion)
        {
            int vResultado = 1;
            string vMensaje = string.Empty;
            string usuario = string.Empty;

            try
            {
                beanSesionUsuario = Session[Common.Constante.session_name.sesionUsuario] as BeanSesionUsuario;
                usuario = beanSesionUsuario.codigoUsuario;

                MensajeDTO mensaje = DetalleCronogramaPagoBL.Instance.Aprobar(lst_detalle, nivel, codigo_resultado, usuario, observacion);

                if (mensaje.idOperacion != 1)
                {
                    vResultado = -1;
                    vMensaje = mensaje.mensaje;
                }
            }
            catch (Exception ex)
            {
                vResultado = -1;
                vMensaje = ex.Message;
            }

            return Json(new { v_resultado = vResultado, v_mensaje = vMensaje }, JsonRequestBehavior.AllowGet);
        }

        #region VISTAS
        [HttpGet]
        [RequiresAuthentication]
        public ActionResult _Detalle(int codigo_detalle)
        {
            detalle_cronograma_aprobacion_dto item = new detalle_cronograma_aprobacion_dto();
            try
            {
                item = DetalleCronogramaPagoSelBL.Instance.ComisionPersonalInactivo(codigo_detalle);
            }
            catch (Exception ex)
            {

                string v_mensaje = ex.Message;
            }

            return PartialView(item);
        }
        #endregion

    }
}

Client/SIGECO-Norte.Web/Areas/Comision/Views/ComisionPersonalInactivo/Index.cshtml
@model SIGEES.Web.Models.Bean.BeanItemTipoAcceso

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<input type="hidden" id="hdCodigoEmpresa" />
<input type="hidden" id="hdNroContrato" />

<div style="width: 99%; background-color: #D3EBDE; vertical-align: middle; padding-top: 2%; padding-bottom: 2%; padding-left: 1%">
    <center>
        <h2>Comisión de Personal Inactivo</h2>
    </center>
    <br />
    <div style="width: 100%">
        <label class="colGridModal">Fecha Inactivación:</label>&nbsp;&nbsp;<label class="colGridModal">Inicio</label>&nbsp;
        <input class="easyui-datebox" id="fechaInicio" name="fechaInicio" style="width:140px;" data-options="required:true" />&nbsp;&nbsp;&nbsp;
        <label class="colGridModal">Fin</label>&nbsp;
        <input class="easyui-datebox" id="fechaFin" name="fechaFin" style="width:140px;" data-options="required:true" />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <label class="colGridModal">Canal de Venta:</label>&nbsp;
        <input class="easyui-combobox" id="codigo_canal" name="codigo_canal" style="width: 20%" data-options="required:true,editable:false,multiple:true" />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <label class="colGridModal">Estado:</label>&nbsp;
        <input class="easyui-combobox" id="cmb_liquidado" name="cmb_liquidado" style="width: 10%" data-options="required:true,editable:false" />
    </div>
    <br />
    <div style="width: 100%">
        @if (Model.estadoLectura.CompareTo("A") == 0)
        {
            <a href="javascript:GetAllJson()" id="btnBuscar" class="easyui-linkbutton" style="padding: 2px 15px 2px 15px; " data-options="iconCls:'icon-search'">Buscar</a>
            <a href="javascript:Detalle()" id="btnDetalle" class="easyui-linkbutton" style="padding: 2px 15px 2px 15px; " data-options="iconCls:'icon-edit'">Detalle</a>
        }            
        @if (Model.estadoComisionInactivaNivel1.CompareTo("A") == 0)
        {
            <a href="javascript:GuardarResultado(1, 1)" id="btnAprobarN1" class="easyui-linkbutton easyui-tooltip" style="padding: 2px 15px 2px 15px; " data-options="iconCls:'icon-ok'" title="Por Comercial">Aprobar</a>
            <a href="javascript:GuardarResultado(1, 2)" id="btnRechazarN1" class="easyui-linkbutton easyui-tooltip" style="padding: 2px 15px 2px 15px; " data-options="iconCls:'icon-cancel'" title="Por Comercial">Rechazar</a>
        }
        @if (Model.estadoComisionInactivaNivel2.CompareTo("A") == 0)
        {
            <a href="javascript:GuardarResultado(2, 1)" id="btnAprobarN2" class="easyui-linkbutton easyui-tooltip" style="padding: 2px 15px 2px 15px; " data-options="iconCls:'icon-ok'" title="Por Administración">Aprobar</a>
            <a href="javascript:GuardarResultado(2, 2)" id="btnRechazarN2" class="easyui-linkbutton easyui-tooltip" style="padding: 2px 15px 2px 15px; " data-options="iconCls:'icon-cancel'" title="Por Administración">Rechazar</a>
        }
        @if (Model.estadoLectura.CompareTo("A") == 0)
        {
            <a href="javascript:ExportarExcel()" id="btnReporte" class="easyui-linkbutton" style="padding: 2px 15px 2px 15px; " data-options="iconCls:'icon-excel'">Exportar</a>
        }
    </div>
</div>
<br />
<div style="width: 99%; padding-left: 1%">
    @if (Model.estadoLectura.CompareTo("A") == 0)
    {
        <table id="DataGrid" style="width: 100%"></table>
    }
</div>

<div id="div_exportar" class="easyui-dialog" data-options="modal:true,closed:true,buttons:'#divRegistroBotones'"
     style="width: 50%; height: 400px; padding: 5px 5px; line-height: 10px;">
</div>

<div id="dlgDetalle" class="easyui-dialog" data-options="modal:true,closed:true,buttons:'#divRegistroBotonesDetalle'"
     style="width: 65%; height: 473px; padding:4px; line-height: 10px;">
</div>

<script type="text/javascript" src="~/Areas/Comision/Scripts/Views/ComisionPersonalInactivo/comisionpersonalinactivo.index.js"></script>

<script type="text/javascript">
    $(document).ready(function () {
        var actionUrls =
        {
            GetFechasJson: '@Url.Action("GetFechasJson", "ComisionPersonalInactivo", new { area = "Comision" })',
            GetAllJson: '@Url.Action("GetAllJson", "ComisionPersonalInactivo", new { area = "Comision" })',
            GetCanalJson: '@Url.Action("GetCanalJson", "ComisionPersonalInactivo", new { area = "Comision" })',
            SetExportData: '@Url.Action("SetExportData", "ComisionPersonalInactivo", new { area = "Comision" })',
            ExportarExcel: '@Url.Action("ExportarExcel", "ComisionPersonalInactivo", new { area = "Comision" })',
            GetLiquidadoJson: '@Url.Action("GetLiquidadoJson", "ComisionPersonalInactivo", new { area = "Comision" })',
            Aprobar: '@Url.Action("Aprobar", "ComisionPersonalInactivo", new { area = "Comision" })',
            _Detalle: '@Url.Action("_Detalle", "ComisionPersonalInactivo", new { area = "Comision" })',
        };
        project.index.Initialize(actionUrls);

    });
</script>