Client/SIGECO-Norte.Web/Areas/Comision/Controllers/ReclamosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using SIGEES.BusinessLogic;
using SIGEES.Entidades;

using SIGEES.Web.Areas.Comision.Services;
using SIGEES.Web.Areas.Comision.Utils;

using SIGEES.Web.Core;
using SIGEES.Web.Models;
using SIGEES.Web.Models.Bean;
using SIGEES.Web.Services;
using SIGEES.Web.Utils;

using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

using SIGEES.Web.Helpers;
using SIGEES.Web.MemberShip.Filters;

namespace SIGEES.Web.Areas.Comision.Controllers
{
    public class ReclamosController : Controller
    {
        private BeanSesionUsuario beanSesionUsuario = new BeanSesionUsuario();
        private readonly ITipoAccesoItemService _tipoAccesoItemService;
        private readonly EstadoReclamoService _EstadoReclamoService;
        private readonly EstadoResultadoService _EstadoResultadoService;
        private readonly reclamoBL _reclamoBL;
        private readonly ArticuloBL _ArticuloBL;
        private readonly EmpresaSIGECOService _EmpresaSIGECOService;
        private readonly PersonalService _personalService;
        private readonly ArticuloService _articuloService;

        protected override void Initialize(System.Web.Routing.RequestContext requestContext)
        {
            base.Initialize(requestContext);
            beanSesionUsuario = Session[Common.Constante.session_name.sesionUsuario] as BeanSesionUsuario;
        }
        public ReclamosController()
        {
            _tipoAccesoItemService = new TipoAccesoItemService();
            _EstadoReclamoService = new EstadoReclamoService();
            _EstadoResultadoService = new EstadoResultadoService();
            _reclamoBL = new reclamoBL();
            _ArticuloBL = new ArticuloBL();
            _EmpresaSIGECOService = new EmpresaSIGECOService();
            _personalService = new PersonalService();
            _articuloService = new ArticuloService();
        }
        [RequiresAuthentication]
        public ActionResult Index()
        {
            BeanItemTipoAcceso bean = new BeanItemTipoAcceso();
            bean = _tipoAccesoItemService.GetBeanItemTipoAcceso(beanSesionUsuario.codigoPerfil);
            return View(bean);
        }

        public ActionResult GetAllEstadoReclamoJson()
        {
            string result = this._EstadoReclamoService.GetAllComboJson();
            return Content(result, "application/json");
        }

        public ActionResult GetAllEstadoResultadoJson()
        {
            string result = this._EstadoResultadoService.GetAllComboJson();
            return Content(result, "application/json");
        }

        public ActionResult GetAllEmpresasJson()
        {
            string result = this._EmpresaSIGECOService.GetAllComboJson();
            return Content(result, "application/json");
        }

        public ActionResult GetPersonalByNombreJson(string texto)
        {
            List<reclamo_personal_listado_dto> lista = new List<reclamo_personal_listado_dto>();

            if (texto != "-1")
            {
                lista =  new PersonalBL().ListarParaReclamos(beanSesionUsuario.codigoUsuario);
            }

            return Content(JsonConvert.SerializeObject(lista), "application/json");
        }

        public ActionResult GetArticulosByNombreJson(string texto)
        {
            string result = _articuloService.GetAllArticulobyNombreJson(texto);
            return Content(result, "application/json");
        }

        [RequiresAuthentication]
        public ActionResult GetAllJson(string nro_contrato, string personal_ventas, string codigo_estado, string codigo_perfil)
        {
            reclamo_busqueda_dto busqueda = new reclamo_busqueda_dto();

            busqueda.nro_contrato = nro_contrato;
            busqueda.personal_ventas = personal_ventas;
            busqueda.codigo_estado = Convert.ToInt32(codigo_estado);
            busqueda.codigo_perfil = Convert.ToInt32(codigo_perfil);
            busqueda.usuario = beanSesionUsuario.codigoUsuario;

            var lista = _reclamoBL.Listar(busqueda);
            return Content(JsonConvert.SerializeObject(lista), "application/json");
        }

        public ActionResult ModificarNotificacionPendientes()
        {
            int result = 0;

            try
            {
                result = new reclamoBL().ObtenerPendientes(beanSesionUsuario.codigoUsuario);
            }
            finally {

            }
            return Json(new { cantidad = result }, JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        public ActionResult Registrar(reclamo_dto v_entidad)
        {
            JObject jo = new JObject();
            reclamo_dto oBE = new reclamo_dto();
            bool esNuevo = v_entidad.codigo_reclamo == -1 ? true : false;
            string[] respuesta = null;

            try
            {
                if (string.IsNullOrEmpty(v_entidad.NroContrato))
                {
                    jo.Add("Msg", "Nro Contrato, Campo requerido");
                    return Content(JsonConvert.SerializeObject(jo), "application/json");
                }

                v_entidad.codigo_personal = v_entidad.codigo_personal;
                v_entidad.NroContrato = string.IsNullOrEmpty(v_entidad.NroContrato) ? "" : v_entidad.NroContrato;
                v_entidad.codigo_articulo = v_entidad.codigo_articulo;
                v_entidad.codigo_empresa = v_entidad.codigo_empresa;
                v_entidad.Cuota = v_entidad.Cuota;
                v_entidad.Importe = v_entidad.Importe;
                v_entidad.codigo_estado_reclamo = 1;
                v_entidad.codigo_estado_resultado = 0;
                v_entidad.Observacion = string.IsNullOrEmpty(v_entidad.Observacion) ? "" : v_entidad.Observacion;
                v_entidad.Respuesta = "";
                v_entidad.usuario_registra = beanSesionUsuario.codigoUsuario;
                v_entidad.fecha_registra = DateTime.Now;
                respuesta = _reclamoBL.Registrar(v_entidad).Split('|');
                if (respuesta.Length == 1)
                {
                    jo.Add("Tipo", "ALERT");
                    jo.Add("Msg", respuesta[0]);
                }
                else if (respuesta.Length == 2)
                {
                    jo.Add("Tipo", respuesta[0]);
                    jo.Add("Msg", respuesta[1]);
                }
                else
                {
                    jo.Add("Tipo", respuesta[0]);
                    jo.Add("Msg", respuesta[1]);
                }
            }
            catch (Exception ex)
            {
                jo.Add("Tipo", "ERROR");
                jo.Add("Msg", ex.ToString());
            }

            return Content(JsonConvert.SerializeObject(jo), "application/json");
        }

        [HttpPost]
        public ActionResult Modificar(reclamo_dto v_entidad)
        {
            JObject jo = new JObject();
            reclamo_dto oBE = new reclamo_dto();
            bool esNuevo = v_entidad.codigo_reclamo == -1 ? true : false;
            int respuesta = -1;

            try
            {
                if (esNuevo)
                {
                    jo.Add("Msg", "Seleccione un registro");
                    return Content(JsonConvert.SerializeObject(jo), "application/json");
                }

                if (string.IsNullOrEmpty(v_entidad.NroContrato))
                {
                    jo.Add("Msg", "Nro Contrato, Campo requerido");
                    return Content(JsonConvert.SerializeObject(jo), "application/json");
                }

                v_entidad.codigo_reclamo = v_entidad.codigo_reclamo;
                v_entidad.codigo_personal = v_entidad.codigo_personal;
                v_entidad.NroContrato = string.IsNullOrEmpty(v_entidad.NroContrato) ? "" : v_entidad.NroContrato;

                v_entidad.codigo_articulo = v_entidad.codigo_articulo;
                v_entidad.codigo_empresa = v_entidad.codigo_empresa;
                v_entidad.Cuota = v_entidad.Cuota;
                v_entidad.Importe = v_entidad.Importe;

                v_entidad.atencion_codigo_articulo = v_entidad.atencion_codigo_articulo;
                v_entidad.atencion_codigo_empresa = v_entidad.atencion_codigo_empresa;
                v_entidad.atencion_Cuota = v_entidad.atencion_Cuota;
                v_entidad.atencion_Importe = v_entidad.atencion_Importe;

                v_entidad.codigo_estado_reclamo = Convert.ToInt32(EstadoReclamo.atendido);         //AppSettings.ReclamoCodResultadoAtendido();             //2: Atendiso
                v_entidad.codigo_estado_resultado = v_entidad.codigo_estado_resultado;
                v_entidad.Observacion = string.IsNullOrEmpty(v_entidad.Observacion) ? "" : v_entidad.Observacion;
                v_entidad.Respuesta = string.IsNullOrEmpty(v_entidad.Respuesta) ? "" : v_entidad.Respuesta;
                v_entidad.usuario_modifica = beanSesionUsuario.codigoUsuario;
                v_entidad.fecha_modifica = DateTime.Now;

                respuesta = _reclamoBL.Actualizar(v_entidad);

                if (respuesta > 0)
                {
                    jo.Add("Msg", "Success");
                }
                else
                {
                    jo.Add("Msg", "NO SE PUDO GUARDAR EL REGISTRO.");
                }
            }
            catch (Exception ex)
            {
                jo.Add("Msg", ex.ToString());
            }

            return Content(JsonConvert.SerializeObject(jo), "application/json");
        }

        [HttpPost]
        public ActionResult Eliminar(string codigo)
        {
            JObject jo = new JObject();
            if (string.IsNullOrWhiteSpace(codigo))
            {
                jo.Add("Msg", "POR FAVOR SELECCIONE UN REGISTRO");
                return Content(JsonConvert.SerializeObject(jo), "application/json");
            }
            try
            {

Client/SIGECO-Norte.Web/Areas/Comision/Views/Reclamos/Index.cshtml
@model SIGEES.Web.Models.Bean.BeanItemTipoAcceso
@using SIGEES.Web.Models.Bean;
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";


    BeanSesionUsuario beanSesionUsuario = Session[SIGEES.Web.Common.Constante.session_name.sesionUsuario] as BeanSesionUsuario;
}

<input type="hidden" id="hdCodigo" />
<input type="hidden" id="hdEstado" />
<input type="hidden" id="hdFila" />
<input type="hidden" id="hdColumna" />
<input type="hidden" id="hdCantidadRegistros" />
<input type="hidden" id="hdPerfil" value="@beanSesionUsuario.codigoPerfil" />

<div style="width: 99%; background-color: #D3EBDE; vertical-align: middle; padding-top: 1%; padding-bottom: 2%; padding-left: 1%">
    <center>
        <h2>Reclamos de Comisión</h2>
    </center>
    <br />
    <div style="width: 100%">
        <table style="width:100%">
            <tr>
                <td style="width:10%;text-align:right">
                    <label class="colGridModal">Nro Contrato&nbsp;&nbsp;</label>
                </td>
                <td style="width:10%">
                    <input class="easyui-textbox" id="NroContrato" name="NroContrato" style="width:90%" />
                </td>
                <td style="width:8%;text-align:right">
                    <label class="colGridModal">Vendedor&nbsp;&nbsp;</label>
                </td>
                <td style="width:25%">
                    <input class="easyui-textbox" id="PersonalVentas" name="PersonalVentas" style="width:90%" />
                </td>
                <td style="width:8%;text-align:right">
                    <label class="colGridModal">Estado&nbsp;&nbsp;</label>
                </td>
                <td style="width:15%">
                    <input class="easyui-combobox" id="cboEstado" name="cboEstado" style="width: 80%" data-options="editable:false" />
                </td>
                <td style="width:24%">
                    &nbsp;
                </td>
            </tr>
        </table>
    </div>
    <br />
    <div style="width: 100%">
        @if (Model.estadoLectura.CompareTo("A") == 0)
        {
            <a href="javascript:void(0)" id="btnBuscar" class="easyui-linkbutton" style="padding: 2px 15px 2px 15px; " data-options="iconCls:'icon-search'">Buscar</a>
            <a href="javascript:void(0)" id="btnVisualizar" class="easyui-linkbutton" style="padding: 2px 15px 2px 15px; " data-options="iconCls:'icon-detail'">Detalle</a>
        }
        @if ((Model.estadoEscritura != null && Model.estadoEscritura.CompareTo("A") == 0) && (Model.estadoReclamoCrear != null && Model.estadoReclamoCrear.CompareTo("A") == 0))
        {
            <a href="javascript:void(0)" id="btnNuevo" class="easyui-linkbutton" style="padding: 2px 15px 2px 15px; " data-options="iconCls:'icon-add'">Crear</a>
        }
        @if ((Model.estadoEscritura != null && Model.estadoEscritura.CompareTo("A") == 0) && (Model.estadoReclamoAtenderN1 != null && Model.estadoReclamoAtenderN1.CompareTo("A") == 0))
        {
            <a href="javascript:void(0)" id="btnAtenderN1" class="easyui-linkbutton" style="padding: 2px 15px 2px 15px; " data-options="iconCls:'icon-edit'" title="Nivel 1">Atender</a>
        }
        @if ((Model.estadoEscritura != null && Model.estadoEscritura.CompareTo("A") == 0) && (Model.estadoReclamoAtenderN2 != null && Model.estadoReclamoAtenderN2.CompareTo("A") == 0))
        {
            <a href="javascript:void(0)" id="btnAtender" class="easyui-linkbutton" style="padding: 2px 15px 2px 15px; " data-options="iconCls:'icon-edit'" title="Nivel 2">Atender</a>
        }
    </div>
</div>
<br>
<div style="width: 99%; padding-left: 1%">
    @if (Model.estadoLectura.CompareTo("A") == 0)
    {
        <table id="DataGrid" style="width: 100%"></table>
    }
</div>

@Html.Partial("_Registro")
@Html.Partial("_Atender")
@Html.Partial("_AtenderN1")
@Html.Partial("_BusquedaPersona")
@Html.Partial("_SeleccionCuota")
@Html.Partial("_Detalle")

@section scripts
{
    <script type="text/javascript" src="~/Areas/Comision/Scripts/Views/Reclamo/project.Reclamo.js"></script>
    <script type="text/javascript">
    $(document).ready(function () {

        var actionUrls =
        {
            GetAllEstadoReclamoJson: '@Url.Action("GetAllEstadoReclamoJson", "Reclamos", new { area = "comision" })',
            GetAllEstadoResultadoJson: '@Url.Action("GetAllEstadoResultadoJson", "Reclamos", new { area = "comision" })',
            GetAllEmpresasJson: '@Url.Action("GetAllEmpresasJson", "Reclamos", new { area = "comision" })',
            GetAllJson: '@Url.Action("GetAllJson", "Reclamos", new { area = "comision" })',
            Registrar: '@Url.Action("Registrar", "Reclamos", new { area = "comision" })',
            Modificar: '@Url.Action("Modificar", "Reclamos", new { area = "comision" })',
            Eliminar: '@Url.Action("Eliminar", "Reclamos", new { area = "comision" })',
            GetRegistro: '@Url.Action("GetRegistro", "Reclamos", new { area = "comision" })',
            GetPersonalByNombreJson: '@Url.Action("GetPersonalByNombreJson", "Reclamos", new { area = "comision" })',
            GetArticulosByFilterJson: '@Url.Action("GetArticulosByFilterJson", "Reclamos", new { area = "comision" })',
            ValidarRegistro: '@Url.Action("ValidarRegistro", "Reclamos", new { area = "comision" })',
            ValidarExisteContratoJson: '@Url.Action("ValidarExisteContratoJson", "Reclamos", new { area = "comision" })',
            ValidarExistePagoJson: '@Url.Action("ValidarExistePagoJson", "Reclamos", new { area = "comision" })',
            _GetArticulosByContratoEmpresaJson: '@Url.Action("GetArticulosByContratoEmpresaJson", "Planilla", new { area = "comision" })',
            _GetDetalleCronogramaPagoByArticuloJson: '@Url.Action("GetDetalleCronogramaPagoByArticuloJson", "Planilla", new { area = "comision" })',
            GetEstadoContratoJson: '@Url.Action("GetEstadoContrato", "Reclamos", new { area = "comision" })',
            AtenderContratoMigrado: '@Url.Action("AtenderContratoMigrado", "Reclamos", new { area = "comision" })',
            AtenderN1: '@Url.Action("AtenderN1", "Reclamos", new { area = "comision" })',
            ModificarNotificacionPendientes: '@Url.Action("ModificarNotificacionPendientes", "Reclamos", new { area = "comision" })',
        };

        project.Reclamo.Initialize(actionUrls);
    });
    </script>
}

Client/SIGECO-Norte.Web/Areas/Comision/Views/Reclamos/_Atender.cshtml
<div id="dlgAtender" class="easyui-dialog" data-options="modal:true,closed:true"
     style="width: 65%; height: 467px; padding: 5px; line-height: 10px;">
	<form id="frmAtender" method="post">
        <input type="hidden" id="hdAtenderEsContratoMigrado" name="hdAtenderEsContratoMigrado" value="">
		<div style="width: 100%; height: 420px;">
            <div class="easyui-layout" style="width:100%; height:100%;">
                <div data-options="region:'center', border:false">
                    <div class="panelGridModal" style="height:auto;">
                        <div class="easyui-panel" title="Reclamo" style="width: 100%;">
                            <table style="width:99%; padding:10px;" border="0">
                                <tr>
                                    <td class="tdEtiqueta">
                                        <label class="colGridModal">Vendedor</label>
                                    </td>
                                    <td class="tdValor">
                                        <input class="easyui-textbox" id="PersonalVentas" name="PersonalVentas" style="width:85%" data-options="required:true,disabled:true" readonly />
                                        <input type="hidden" id="hdCodigoPersonal" />
                                    </td>
                                    <td class="tdEtiqueta">
                                        <label class="colGridModal">Contrato</label>
                                    </td>
                                    <td class="tdValor">
                                        <input class="easyui-textbox" id="NroContrato" name="NroContrato" style="width:120px" data-options="required:true,disabled:true" readonly />
                                    </td>
                                </tr>
                                <tr>
                                    <td class="tdEtiqueta">
                                        <label class="colGridModal">Empresa</label>
                                    </td>
                                    <td class="tdValor">
                                        <input class="easyui-combobox" id="cboEmpresa_1" name="cboEmpresa_1" style="width: 85%" data-options="required:true,disabled:true,editable:false" readonly />
                                    </td>
                                    <td class="tdEtiqueta">
                                        <label class="colGridModal">Articulo</label>
                                    </td>
                                    <td class="tdValor">
                                        <input class="easyui-textbox" id="Articulo_1" name="Articulo_1" style="width:100%" data-options="required:true,disabled:true" readonly />
                                        <input type="hidden" id="hdCodigoArticulo_1" />
                                    </td>
                                </tr>
                                <tr>
                                    <td class="tdEtiqueta">
                                        <label class="colGridModal">Cuota</label>
                                    </td>
                                    <td class="tdValor">
                                        <input class="easyui-numberbox" id="Cuota_1" name="Cuota_1" style="width: 120px" data-options="required:true,disabled:true" />
                                    </td>
                                    <td class="tdEtiqueta">
                                        <label class="colGridModal">Importe</label>
                                    </td>
                                    <td class="tdValor">
                                        <input class="easyui-numberbox" id="Importe_1" name="Importe_1" style="width: 120px" data-options="required:true,disabled:true, min:0,max:9999999.99,precision:2" />
                                    </td>
                                </tr>
                                <tr>
                                    <td class="tdEtiqueta">
                                        <label class="colGridModal">Error Contrato</label>
                                    </td>
                                    <td class="tdValor">
                                        <input class="easyui-textbox" id="es_contrato_migrado" name="es_contrato_migrado" style="width:120px" data-options="disabled:true" readonly />
                                    </td>
                                    <td class="tdEtiqueta" colspan="2">
                                        &nbsp;
                                    </td>
                                </tr>
                                <tr>
                                    <td class="tdEtiqueta">
                                        <label class="colGridModal">Observación</label>
                                    </td>
                                    <td style="width: 85%;" colspan="3">
                                        <input class="easyui-textbox" id="Observacion_1" name="Observacion_1" style="width: 100%; height: 40px; " data-options="multiline:true,required:true,disabled:true" />
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>                                
                    <div class="panelGridModal" style="height:auto;">
                        <div class="easyui-panel" title="Atención" style="width: 100%;">
                            <table style="width:99%; padding:10px;" border="0">
                                <tr>
                                    <td class="tdEtiqueta">
                                        <label class="colGridModal">Cuota</label>
                                    </td>
                                    <td class="tdValor">
                                        <input class="easyui-numberbox" id="Cuota_2" name="Cuota_2" style="width: 120px" data-options="required:true, disabled:true" readonly />
                                    </td>
                                    <td class="tdEtiqueta">
                                        <label class="colGridModal">Importe</label>
                                    </td>
                                    <td class="tdValor">
                                        <input class="easyui-numberbox" id="Importe_2" name="Importe_2" style="width: 120px" data-options="required:true, min:0,max:9999999.99,precision:2" />
                                    </td>
                                </tr>
                                <tr>
                                    <td class="tdEtiqueta">
                                        <label class="colGridModal">Estado</label>
                                    </td>
                                    <td class="tdValor">
                                        <input class="easyui-combobox" id="cboEstado_2" name="cboEstado_2" style="width: 120px" data-options="required:true,disabled:true,editable:false" />
                                    </td>
                                    <td class="tdEtiqueta">
                                        <label class="colGridModal">Resultado</label>
                                    </td>
                                    <td class="tdValor">
                                        <input class="easyui-combobox" id="cboResultado_2" name="cboResultado_2" style="width: 120px" data-options="required:true,editable:false" />
                                    </td>
                                </tr>
                                <tr>
                                    <td class="tdEtiqueta">
                                        <label class="colGridModal">Respuesta</label>
                                    </td>
                                    <td style="width: 85%;" colspan="3">
                                        <input class="easyui-textbox" id="Respuesta_2" name="Respuesta_2" style="width: 100%; height: 40px; " data-options="multiline:true,required:true" />
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>

                </div>
                <div data-options="region:'south', border:false" style="text-align: right; vertical-align: central; height: 40px; padding: 5px; ">
                    <a href="#" class="easyui-linkbutton" style="padding: 0px 10px 0px 10px; " iconcls="icon-ok" id="btnGuardar">Guardar</a>
                    <a href="#" class="easyui-linkbutton" style="padding: 0px 10px 0px 10px; " iconcls="icon-cancel" id="btnCancelar">Cancelar</a>
                </div>
            </div>
        </div>
			
	</form>
</div>
<style>
    .tdEtiqueta {
        width: 15%;
        padding: 5px;
    }

    .tdValor {
        width: 35%;
    }
</style>

Client/SIGECO-Norte.Web/Areas/Comision/Views/Reclamos/_BusquedaArticulo.cshtml
<div id="dlgBusquedaArticulo" class="easyui-dialog" data-options="modal:true,closed:true,buttons:'#dlgBusquedaArticuloBotones'"
     style="width: 50%; height: 60%; padding: 10px 20px; line-height: 20px;">

    <div class="easyui-layout" data-options="fit:true">
        <form id="frmBusquedaArticulo" method="post">
            <div data-options="region:'center'" style="padding:10px;">
                <br />
                <hr style="color: #B5B5B5; width:96%" />
                <div class="panelGridModal">
                    <div class="rowGridModalDouble">
                        <input class="easyui-textbox" id="ArticuloNombre" name="ArticuloNombre" data-options="buttonText:'Buscar Articulo',buttonAlign:'right',buttonIcon:'icon-search'" style="width:100%;">
                    </div>
                    <div class="rowGridModalDouble">
                        <label class="colGridModal">Lista Articulos</label>
                        <table id="dgArticulos" style="width: 100%"></table>
                    </div>
                    <div class="rowBoth" />
                </div>
                <br />
                <hr style="color: #B5B5B5; width:96%" />

            </div>
            <div id="dlgBusquedaArticuloBotones">
                <a href="#" class="easyui-linkbutton" iconcls="icon-ok" id="btnSeleccionar">Seleccionar</a>
                <a href="#" class="easyui-linkbutton" iconcls="icon-cancel" id="btnCancelar">Cancelar</a>
            </div>
        </form>
    </div>
</div>

Client/SIGECO-Norte.Web/Areas/Comision/Views/Reclamos/_BusquedaPersona.cshtml
<div id="dlgBusquedaPersona" class="easyui-dialog" data-options="modal:true,closed:true"
     style="width: 60%; height: 80%; line-height: 20px;">

    <div class="easyui-layout" data-options="fit:true">
        <div data-options="region:'center',border:false" style="padding:10px;">
            <table id="dgPersonas" style="width: 100%;height:100%"></table>
        </div>
        <div data-options="region:'south'" style="padding:10px;">
            <div style="height:100%">
                <label class="colGridModal" style="color:#f56363;">(*) Para seleccionar un vendedor haga doble click sobre el registro.</label>
            </div>
        </div>
    </div>
</div>

Client/SIGECO-Norte.Web/Areas/Comision/Views/Reclamos/_SeleccionCuota.cshtml
<div id="dlgSeleccionCuota" class="easyui-dialog" data-options="modal:true,closed:true,maximizable:true, resizable: true"
     style="width: 65%; height: 90%; ">

    <div class="easyui-layout" data-options="fit:true">
        <div data-options="region:'north', border:false" style="padding:10px;height:60px">
            <form id="frmSelecionCuota" method="post">
                <input type="hidden" id="codigo_estado_proceso" name="codigo_estado_proceso">
                <div style="height:100%;">
                    <div class="rowGridModal">
                        <label class="colGridModal">Estado</label>
                        <input class="easyui-textbox" id="nombre_estado_proceso" name="nombre_estado_proceso" style="width:80%" data-options="disabled:true" />
                    </div>
                    <div class="rowGridModal">
                        <label class="colGridModal">Observación</label>
                        <input class="easyui-textbox" id="observacion" name="observacion" style="width:80%" data-options="disabled:true" />
                    </div>
                </div>
            </form>
        </div>
        <div data-options="region:'center', border:false" style="padding:10px;">
            <table id="dgv_analisis_contrato_articulo" style="width: 100%; height:45%;"></table>
            <table id="dgv_contrato_detalle_pago" style="width: 100%; height:55%;"></table>
        </div>
        <div data-options="region:'south'" style="padding:5px;height:40px">
            <div style="height:100%;">
                <div id="divSeleccionCuota" style="vertical-align:middle;display:none">
                    <label class="colGridModal" style="color:#f56363;">(*) Para seleccionar una cuota haga doble click sobre el registro.</label>
                </div>
                <div id="divSeleccionContrato" style="text-align:right;vertical-align:middle;display:none">
                    <a href="#" class="easyui-linkbutton" style="padding: 0px 10px 0px 10px; " iconcls="icon-ok" id="btnSeleccionarCuotaComision">Seleccionar Contrato</a>
                </div>
            </div>
        </div>
    </div>
</div>