Client/SIGECO-Norte.Web/Areas/Comision/Models/PlanillaViewModel.cs
using SIGEES.Entidades;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using SIGEES.Web.Models.Bean;

namespace SIGEES.Web.Areas.Comision.Models
{
    public class PlanillaViewModel
    {

        public PlanillaViewModel()
        {
            planilla = new Planilla_dto();
            planilla_bono = new Planilla_bono_dto();
            planilla_bono_trimestral = new planilla_bono_trimestral_dto();
            bean = new BeanItemTipoAcceso();
        }
        public Planilla_dto planilla { set; get; }
        public Planilla_bono_dto planilla_bono { set; get; }
        public planilla_bono_trimestral_dto planilla_bono_trimestral { set; get; }
        public BeanItemTipoAcceso bean { set; get; }
    }
}

Client/SIGECO-Norte.Web/Areas/Comision/Models/ReporteViewModel.cs
using SIGEES.Entidades;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SIGEES.Web.Areas.Comision.Models
{
    public class ReporteViewModel
    {

        public ReporteViewModel()
        {
            
        }
        public string url { set; get; }
        public int codigo_planilla{set;get;}
        public int codigo_personal { set; get; }
    }
}

Client/SIGECO-Norte.Web/Areas/Comision/Controllers/PlanillaComercialController.cs
using Microsoft.Reporting.WebForms;
using Newtonsoft.Json;
using SIGEES.BusinessLogic;
using SIGEES.Entidades;
using SIGEES.Entidades.planilla;
using SIGEES.Web.Areas.Comision.Models;
using SIGEES.Web.Areas.Comision.Services;
using SIGEES.Web.MemberShip.Filters;
using SIGEES.Web.Models.Bean;
using SIGEES.Web.Services;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace SIGEES.Web.Areas.Comision.Controllers
{
    public class PlanillaComercialController : Controller
    {
        private BeanSesionUsuario beanSesionUsuario = new BeanSesionUsuario();
        private readonly ITipoAccesoItemService _tipoAccesoItemService;
        private readonly CanalGrupoService _canalService;
        private readonly TipoPlanillaService _tipoPlanillaService;

        //
        // GET: /Comision/Planilla/
        //protected override void Initialize(System.Web.Routing.RequestContext requestContext)
        //{
        //    base.Initialize(requestContext);
        //    beanSesionUsuario = Session[Common.Constante.session_name.sesionUsuario] as BeanSesionUsuario;
        //}
        public PlanillaComercialController()
        {
            _tipoAccesoItemService = new TipoAccesoItemService();
            _canalService = new CanalGrupoService();
            _tipoPlanillaService = new TipoPlanillaService();

        }

        public ActionResult GetCanalJson()
        {
            string result = this._canalService.GetCanalAllComboJson();
            return Content(result, "application/json");
        }
        public ActionResult GetTipoPlanillaJson()
        {
            string result = this._tipoPlanillaService.GetAllComboJson();
            return Content(result, "application/json");
        }
        [RequiresAuthentication]
        public ActionResult Index()
        {
            BeanItemTipoAcceso bean = new BeanItemTipoAcceso();
            try
            {
                beanSesionUsuario = Session[Common.Constante.session_name.sesionUsuario] as BeanSesionUsuario;
                bean = _tipoAccesoItemService.GetBeanItemTipoAcceso(beanSesionUsuario.codigoPerfil);
            }
            catch (Exception ex)
            {

                ex.ToString();
            }


            return View(bean);
        }

        public ActionResult GetComboReglaTipoPlanillaAllJson()
        {
            List<combo_regla_tipo_planilla_dto> result = ReglaTipoPlanillaBL.Instance.GetAllComboJson();
            return Content(JsonConvert.SerializeObject(result), "application/json");
        }

        [HttpPost]
        public ActionResult GetPagosHabilitadoJson(int codigo_planilla)
        {
            List<detalle_planilla_resumen_dto> lst = new List<detalle_planilla_resumen_dto>();
            try
            {
                
                lst = DetallePlanillaSelBL.Instance.ListarPagoHabilitadoByIdPlanilla(codigo_planilla);
            }
            catch (Exception ex)
            {

                string mensaje = ex.Message;
            }
            return Content(JsonConvert.SerializeObject(lst), "application/json");

        }



        [HttpGet]
        [RequiresAuthentication]
        public ActionResult _Planilla(int p_codigo_planilla)
        {
            PlanillaViewModel vm = new PlanillaViewModel();

            vm.planilla = PlanillaSelBL.Instance.BuscarById(p_codigo_planilla);


            return PartialView(vm);
        }


        public ActionResult _Liquidacion(string p_codigo_planilla, string p_codigo_personal)
        {

            ReporteViewModel vm = new ReporteViewModel();
            try
            {
                string urlReporte = Url.Action("frm_reporte_liquidacion", "Areas/Comision/Reporte/Planilla/frm", new { area = string.Empty }) + ".aspx?p_codigo_planilla=" + p_codigo_planilla + "&p_codigo_personal=" + p_codigo_personal;
                vm.url = urlReporte;
            }
            catch (Exception ex)
            {
                string mensa = ex.Message;
            }
            return PartialView("_Reporte", vm);
        }

        public ActionResult _Reporte(int p_codigo_planilla,int p_codigo_personal)
        {
            ReporteViewModel vm = new ReporteViewModel();  
            
            try
            {
                string urlReporte = Url.Action("frm_reporte_liquidacion", "Areas/Comision/Reporte/Planilla/frm") + ".aspx?p_codigo_planilla=" + p_codigo_planilla + "& codigo_personal=" + p_codigo_personal;
                vm.url = urlReporte;
            }
            catch (Exception ex)
            {
                string mensa = ex.Message;
            }
            return PartialView("_Reporte", vm);
        }


        public ActionResult _Exportar(int p_codigo_planilla)
        {
            ReporteViewModel vm = new ReporteViewModel();           
            try
            {
                string urlReporte = Url.Action("frm_reporte_planilla_comercial", "Areas/Comision/Reporte/PlanillaComercial/frm", new { area = string.Empty }) + ".aspx?p_codigo_planilla=" + p_codigo_planilla;
                vm.url = urlReporte;
            }
            catch (Exception ex)
            {
                string mensa = ex.Message;
            }
            return PartialView("_Reporte",vm);
        }



    }
}

Client/SIGECO-Norte.Web/Areas/Comision/Controllers/PlanillaController.cs
using log4net;
using Microsoft.Reporting.WebForms;
using Newtonsoft.Json;
using SIGEES.BusinessLogic;
using SIGEES.Entidades;
using SIGEES.Entidades.planilla;
using SIGEES.Web.Areas.Comision.Models;
using SIGEES.Web.Areas.Comision.Services;
using SIGEES.Web.MemberShip.Filters;
using SIGEES.Web.Models.Bean;
using SIGEES.Web.Services;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Text;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using SIGEES.Web.Areas.Comision.Utils;
using ClosedXML.Excel;
using System.Web.Hosting;
using System.Configuration;

namespace SIGEES.Web.Areas.Comision.Controllers
{
    //[SessionExpireFilter]
    //[SessionExpireFilterAttribute]

    [RequiresAuthenticationAttribute]
    public class PlanillaController : Controller
    {
        private BeanSesionUsuario beanSesionUsuario = new BeanSesionUsuario();
        private readonly ITipoAccesoItemService _tipoAccesoItemService;

        private readonly CanalGrupoService _canalService;
        private readonly TipoPlanillaService _tipoPlanillaService;
        private readonly EmpresaSIGECOService _empresaSIGECOService;
        private readonly IParametroSistemaService _IParametroSistemaService;
        private readonly TipoVentaService _tipoVentaService;

        LocalReport rptLiquidacion;
        LocalReport rptResumenLiquidacion;

        private static readonly log4net.ILog log = log4net.LogManager.GetLogger(typeof(PlanillaController));

        //
        // GET: /Comision/Planilla/
        //protected override void Initialize(System.Web.Routing.RequestContext requestContext)
        //{
        //    base.Initialize(requestContext);
        //    beanSesionUsuario = Session[Common.Constante.session_name.sesionUsuario] as BeanSesionUsuario;
        //}
        public PlanillaController()
        {
            _tipoVentaService = new TipoVentaService();
            _tipoAccesoItemService = new TipoAccesoItemService();
            _canalService = new CanalGrupoService();
            _tipoPlanillaService = new TipoPlanillaService();
            _empresaSIGECOService = new EmpresaSIGECOService();
            _IParametroSistemaService = new ParametroSistemaService();
          //  GenerarComisionExcel(50);
        }

        [RequiresAuthentication]
        public ActionResult GetCanalJson()
        {
            string result = this._canalService.GetCanalAllComboJson();
            return Content(result, "application/json");
        }
        public ActionResult GetEmpresaByContratoJson(string p_numero_contrato)
        {
            filtro_contrato_dto busqueda = new filtro_contrato_dto { numero_contrato = p_numero_contrato };
            List<analisis_contrato_combo_dto> result = ContratoSelBL.Instance.ListarEmpresasByContrato(busqueda);
            return Content(JsonConvert.SerializeObject(result), "application/json");
        }

        public ActionResult GetTipoPlanillaJson()
        {
            string result = this._tipoPlanillaService.GetAllComboJson();
            return Content(result, "application/json");
        }

        public ViewResult Index()
        {
            BeanItemTipoAcceso bean = new BeanItemTipoAcceso();
            try
            {
                beanSesionUsuario = Session[Common.Constante.session_name.sesionUsuario] as BeanSesionUsuario;
                bean = _tipoAccesoItemService.GetBeanItemTipoAcceso(beanSesionUsuario.codigoPerfil);
            }
            catch (Exception ex)
            {

                ex.ToString();
            }


            return View(bean);
        }

        public ActionResult GetFilterTipoVentaJson()
        {
            string result = this._tipoVentaService.GetComboFilterAbreaviaturaJson();
            return Content(result, "application/json");
        }
        public ActionResult GetComboReglaTipoPlanillaAllJson()
        {
            List<combo_regla_tipo_planilla_dto> result = ReglaTipoPlanillaBL.Instance.GetAllComboJson();
            return Content(JsonConvert.SerializeObject(result), "application/json");
        }

        [HttpPost]
        public ActionResult _Buscar()
        {

            var query = new object();
            int v_resultado = 1;
            string v_mensaje = "";
            int v_total = 0;
            try
            {
                var lst = PlanillaSelBL.Instance.Listar();
                v_total = lst.Count();
                query = from order in lst.AsEnumerable()
                        select new
                        {
                            codigo_planilla = order.codigo_planilla,
                            numero_planilla = order.numero_planilla,
                            nombre_regla_tipo_planilla = order.nombre_regla_tipo_planilla,
                            nombre_tipo_planilla = order.tipo_planilla.nombre,
                            fecha_inicio = order.fecha_inicio.ToShortDateString(),
                            fecha_fin = order.fecha_fin.ToShortDateString(),
                            nombre_estado_planilla = order.estado_planilla.nombre,
                            fecha_apertura = order.fecha_apertura.ToShortDateString(),
                            codigo_estado_planilla = order.codigo_estado_planilla,
                            fecha_cierre = order.fecha_cierre == null ? "" : DateTime.Parse(order.fecha_cierre.ToString()).ToShortDateString(),
                            fecha_anulacion = order.fecha_anulacion == null ? "" : DateTime.Parse(order.fecha_anulacion.ToString()).ToShortDateString(),
                            estilo = order.estilo,
                            envio_liquidacion = (order.envio_liquidacion ? 1 : 0)
                        };
            }
            catch (Exception ex)
            {
                ex.ToString();
                v_resultado = -1;
                v_mensaje = ex.Message;
            }
            var jsonResult = Json(new
            {
                v_resultado = v_resultado,
                v_mensaje = v_mensaje,
                total = v_total,
                rows = query

            }, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = int.MaxValue;
            return jsonResult;
        }

        [HttpPost]
        public ActionResult GetPagosHabilitadoJson(detalle_planilla_resumen_dto v_planilla)
        {
            List<detalle_planilla_resumen_dto> lst = new List<detalle_planilla_resumen_dto>();
            try
            {

                lst = DetallePlanillaSelBL.Instance.ListarByIdPlanilla(v_planilla);
            }
            catch (Exception ex)
            {

                string mensaje = ex.Message;
            }
            return Content(JsonConvert.SerializeObject(lst), "application/json");

        }

        #region GENERAR EXCEL - COMISIONES
        public byte[] ReadFileToBytes(string sPathFile)
        {
            using (FileStream fileStream = new FileStream(sPathFile, FileMode.Open, FileAccess.Read))
            {
                byte[] bytes = new byte[(int)fileStream.Length];
                fileStream.Read(bytes, 0, (int)fileStream.Length);
                fileStream.Close();
                return bytes;
            }
        }
        public void GenerarComisionExcel(int p_codigo_planilla)
        {
            List<detalle_planilla_resumen_dto> lst = new List<detalle_planilla_resumen_dto>();
            detalle_planilla_resumen_dto v_planilla = new detalle_planilla_resumen_dto();
            v_planilla.codigo_planilla = p_codigo_planilla;

            Random random = new Random();
            int numRandom = random.Next(1000, 99999);
            var FileName = $"Comision_{numRandom}.xlsx";

            try
            {

                lst = DetallePlanillaSelBL.Instance.ListarByIdPlanilla(v_planilla);
                // string urlPlantilla = Server.MapPath("~/Plantilla/plantilla_comision_chiclayo.xlsx");
                string urlPlantilla = HostingEnvironment.MapPath("~/Plantilla/plantilla_comision_chiclayo.xlsx");

                string urlBase = HostingEnvironment.MapPath("~/Plantilla/");
                var array = ReadFileToBytes(urlPlantilla);
                using (var stream = new MemoryStream(array))
                {
                    using (XLWorkbook workbook = new XLWorkbook(stream))
                    {
                        IXLWorksheet worksheet = workbook.Worksheets.Add($"comision-15");
                        worksheet.Cell("A5").Value = "Tipo Contrato";
                        worksheet.Cell("B5").Value = "Tipo Servicio";
                        worksheet.Cell("C5").Value = "Tarifa Parcel";
                        worksheet.Cell("D5").Value = "Propuesta";
                        worksheet.Cell("E5").Value = "Fecha";
                        worksheet.Cell("F5").Value = "Total Venta";
                        worksheet.Cell("G5").Value = "Anticipo";
                        worksheet.Cell("H5").Value = "% de inicial Comisión";
                        worksheet.Cell("I5").Value = "% Comisión";


                        
                            workbook.SaveAs(Path.Combine(urlBase, Path.Combine("Temp", FileName)));
                        
                        
                    }
                }





            }
            catch (Exception ex)
            {

                string mensaje = ex.Message;
            }

        }
        #endregion


        [HttpPost]
        public ActionResult GetPagosComisionManualJson(detalle_planilla_resumen_dto v_planilla)
        {
            List<detalle_planilla_resumen_dto> lst = new List<detalle_planilla_resumen_dto>();
            try
            {

                lst = DetallePlanillaSelBL.Instance.ListarComisionManualByIdPlanilla(v_planilla);
            }
            catch (Exception ex)
            {

                string mensaje = ex.Message;

Client/SIGECO-Norte.Web/Areas/Comision/Views/PlanillaComercial/Index.cshtml
@model SIGEES.Web.Models.Bean.BeanItemTipoAcceso

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div style="width: 99%;background-color: #D3EBDE; vertical-align: middle; padding-top: 1%; padding-bottom: 2%; padding-left: 1%">
    <center>
        <h2>Consulta de Planilla de Comisiones</h2>
    </center>
    <div style="width:100%" id="toolbar_planilla_opcion">
        @if (Model.estadoLectura != null && Model.estadoLectura.CompareTo("A") == 0)
        {
            <a href="javascript:fnConsultarPlanilla()" class="easyui-linkbutton" style="padding: 2px 15px 2px 15px; " data-options="iconCls:'icon-search'">Buscar</a>
        }
        @if (Model.estadoEscritura != null && Model.estadoEscritura.CompareTo("A") == 0)
        {
            <a href="javascript:fnPlanillaComercial()" class="easyui-linkbutton" style="padding: 2px 15px 2px 15px; " data-options="iconCls:'icon-detail'">Detalle</a>
        }
    </div>
</div>
<br />

<div style="width: 99%; padding-left: 1%">

    <table id="dgv_planilla_comercial" style="width: 100%"></table>

</div>
<div id="div_planilla_comercial" class="easyui-dialog" data-options="resizable:true,modal:true,closed:true"
     style="width: 70%; height: 95%;line-height: 15px;"></div>
@section scripts
{
    <script type="text/javascript" src="~/Scripts/Aditional/datagrid-bufferview.js"></script>
    <script type="text/javascript" src="~/Areas/Comision/Scripts/Views/PlanillaComercial/planilla_comercial.index.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {

            var actionUrls =
            {
                _Buscar: '@Url.Action("_Buscar", "Planilla", new { area =string.Empty })',
                _Planilla: '@Url.Action("_Planilla", "PlanillaComercial", new { area ="Comision"})',
                _GetCanalJson: '@Url.Action("GetCanalJson", "Planilla", new { area = string.Empty })',
            };

            project.index.Initialize(actionUrls);
        });
    </script>
}

Client/SIGECO-Norte.Web/Areas/Comision/Views/PlanillaComercial/_Planilla.cshtml
@model SIGEES.Web.Areas.Comision.Models.PlanillaViewModel
@{
    int codigo_planilla = Model.planilla.codigo_planilla;
    string fecha_actual = DateTime.Now.ToShortDateString();

}

<div class="easyui-layout" data-options="fit:true">
    <div data-options="region:'north', border:false" style="padding:5px 5px 0px 5px;height:225px;">
        <div class="easyui-layout" data-options="fit:true">
            <div data-options="region:'center',border:false" style="width:100%">
                <div class="easyui-layout" data-options="fit:true">
                    <div class="easyui-panel" title="Datos Generales" style="width: 99%; ">
                        <div class="rowGridModalDouble" style="width:12%;">
                            <label class="colGridModal">N&uacute;mero Planilla</label>
                        </div>
                        <div class="rowGridModalDouble" style="width:15%;">
                            <input class="easyui-textbox" type="text" value="@Model.planilla.numero_planilla" style="width: 100%;" data-options="disabled:true" id="txt_numero_planilla" />
                        </div>
                        <div class="rowGridModalDouble" style="width:12%;">
                            <label class="colGridModal">Planilla</label>
                        </div>
                        <div class="rowGridModalDouble" style="width:15%;">
                            @if (codigo_planilla > 0)
                        {
                            <input id="cmb_regla_tipo_planilla" value="@Model.planilla.codigo_regla_tipo_planilla" class="easyui-combobox" style="width:100%;" data-options="required:true,novalidate:true,editable:false,disabled:true">
                        }
                        else
                        {
                            <input id="cmb_regla_tipo_planilla" class="easyui-combobox" style="width:100%;" data-options="required:true,novalidate:true,editable:false">
                        }
                        </div>
                        <div class="rowGridModalDouble" style="width:12%;">
                            <label class="colGridModal">Tipo Planilla</label>
                        </div>
                        <div class="rowGridModalDouble" style="width:15%;">

                            <input id="cmb_tipo_planilla" value="@Model.planilla.codigo_tipo_planilla" class="easyui-combobox" style="width:100%;" data-options="required:true,novalidate:true,editable:false,disabled:true">

                        </div>
                        <!--segunda linea-->
                        <div class="rowBoth"></div>
                        <div class="rowGridModalDouble" style="width:12%;">
                            <label class="colGridModal">Fecha Inicio</label>
                        </div>
                        <div class="rowGridModalDouble" style="width:15%;">
                            @if (codigo_planilla > 0)
                        {
                            <input class="easyui-datebox" type="text" value="@Model.planilla.fecha_inicio" style="width: 100%;"
                                   data-options="required:true,disabled:true,novalidate:true,validType:'fechaMenorAHoyYMenorA[\'#dtp_fecha_fin\',\'Fecha Fin\',\'dd/MM/yyyy\']'" id="dtp_fecha_inicio" />
                        }
                        else
                        {

                            <input class="easyui-datebox" type="text" style="width: 100%;"
                                   data-options="required:true,editable: false,novalidate:true,validType:'fechaMenorAHoyYMenorA[\'#dtp_fecha_fin\',\'Fecha Fin\',\'dd/MM/yyyy\']'" id="dtp_fecha_inicio" />

                        }
                        </div>
                        <div class="rowGridModalDouble" style="width:12%;">
                            <label class="colGridModal">Fecha Fin</label>
                        </div>
                        <div class="rowGridModalDouble" style="width:15%;">
                            @if (codigo_planilla > 0)
                        {
                            <input class="easyui-datebox" type="text" value="@Model.planilla.fecha_fin" style="width: 100%;"
                                   data-options="required:true,disabled:true,novalidate:true,validType:'MenorIgualAHoy[\'dd/MM/yyyy\',\'#dtp_fecha_fin\']'" id="dtp_fecha_fin" />
                        }
                        else
                        {
                            <input class="easyui-datebox" type="text" value="@fecha_actual" style="width: 100%;"
                                   data-options="required:true,editable: false,novalidate:true,validType:'MenorIgualAHoy[\'dd/MM/yyyy\',\'#dtp_fecha_fin\']'" id="dtp_fecha_fin" />
                        }
                        </div>
                        <div class="rowGridModalDouble" style="width:12%;">
                            <label class="colGridModal">Estado</label>
                        </div>
                        <div class="rowGridModalDouble" style="width:15%;">
                            <input class="easyui-textbox" type="text" value="@Model.planilla.estado_planilla.nombre" style="width: 100%;" data-options="disabled:true" />
                        </div>
                    </div>
                    <div class="easyui-panel" title="Datos de Auditoria" style="width: 99%; ">
                        <div class="rowGridModalDouble" style="width:12%;">
                            <label class="colGridModal">Fecha Apertura</label>
                        </div>
                        <div class="rowGridModalDouble" style="width:15%;">
                            <input class="easyui-textbox" type="text" value="@Model.planilla.fecha_apertura.ToString("dd/MM/yyyy HH:mm:ss")" style="width: 100%;" data-options="disabled:true" />
                        </div>
                        <div class="rowGridModalDouble" style="width:12%;">
                            <label class="colGridModal">Usuario</label>
                        </div>
                        <div class="rowGridModalDouble" style="width:40%;">
                            <input class="easyui-textbox" type="text" value="@Model.planilla.usuario_apertura" style="width: 100%;" data-options="disabled:true" />
                        </div>
                        <!--segunda linea-->
                        <div class="rowBoth"></div>
                        <div class="rowGridModalDouble" style="width:12%;">
                            <label class="colGridModal">Fecha Cierre</label>
                        </div>
                        <div class="rowGridModalDouble" style="width:15%;">
                            @{

                            string v_fecha_cierre = Model.planilla.fecha_cierre == null ? "" : DateTime.Parse(Model.planilla.fecha_cierre.ToString()).ToString("dd/MM/yyyy HH:mm:ss");

                            }
                            <input class="easyui-textbox" type="text" value="@v_fecha_cierre" style="width: 100%;" data-options="disabled:true" />
                        </div>
                        <div class="rowGridModalDouble" style="width:12%;">
                            <label class="colGridModal">Usuario</label>
                        </div>
                        <div class="rowGridModalDouble" style="width:40%;">
                            <input class="easyui-textbox" type="text" value="@Model.planilla.usuario_cierre" style="width: 100%;" data-options="disabled:true" />
                        </div>
                    </div>
                </div>
            </div>
            <div data-options="region:'east',border:false" style="width:200px">
                <div class="easyui-panel" title="Opciones" style="width: 98%; ">
                    @*<a href="javascript:fnExportarPlanilla(@Model.planilla.codigo_planilla);" class="easyui-linkbutton" iconcls="icon-print" style="text-align: left; padding: 2px 0px 2px 15px; width: 99%">Reporte</a>*@
                    <a href="javascript:fnReporteLiquidacion(@Model.planilla.codigo_planilla);" class="easyui-linkbutton" iconcls="icon-print" style="text-align: left; padding: 2px 0px 2px 15px; width: 99%">Liquidaciones</a>
                    <a href="javascript:cerrar_planilla();" class="easyui-linkbutton" iconcls="icon-undo" style="text-align: left; padding: 2px 0px 2px 15px; width: 99%">Salir</a>
                </div>
            </div>
        </div>
    </div>
    <div data-options="region:'center',border:false" style="padding:0px 5px 5px 5px;">
        <div class="easyui-panel" title="Detalle Planilla" style="height:100%;">
            <table id="dgv_planilla_comercial_pago_habilitado" style="width:100%;height:100%"></table>
        </div>
    </div>
</div>

<div id="div_reporte_general" class="easyui-dialog" data-options="resizable:true,modal:true,closed:true"
     style="width: 100%; height: 100%;line-height: 20px;"></div>

<script type="text/javascript" src="~/Areas/Comision/Scripts/Views/PlanillaComercial/planilla_comercial.planilla.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        var actionUrls =
        {
            _Reporte: '@Url.Action("_Reporte", "Planilla", new { area = "Comision" })',
            _Reporte_Liquidacion: '@Url.Action("_Liquidacion", "PlanillaComercial", new { area = "Comision" })',
            _Exportar: '@Url.Action("_Exportar", "PlanillaComercial", new { area = "Comision" })',
            _GetReglaTipoPlanillaJson: '@Url.Action("GetComboReglaTipoPlanillaAllJson", "PlanillaComercial", new { area = string.Empty })',
            _GetTipoPlanillaJson: '@Url.Action("GetTipoPlanillaJson", "Planilla", new { area = string.Empty })',
            _GetPagoHabilitadoJson: '@Url.Action("GetPagosHabilitadoJson", "PlanillaComercial", new { area = string.Empty })',
            _codigo_planilla: '@codigo_planilla',
            _numero_planilla: '@Model.planilla.numero_planilla'
        };
        project.planilla.Initialize(actionUrls);
    });
</script>

Client/SIGECO-Norte.Web/Areas/Comision/Views/PlanillaComercial/_Reporte.cshtml
@model SIGEES.Web.Areas.Comision.Models.ReporteViewModel
<script type="text/javascript">    
    $(document).ready(function () {

        $('.content').ResizeModal({
            widthMax: '100%',
            widthMin: '100%',
            div: 'div_reporte_general'
        });

        var iframe = "<iframe id='ifReporte' width='100%' style='position: absolute; height: 95vh; border: none' frameborder='0'src='" + '@Model.url' + "'></iframe>";
        $("#frame_reporte_general").html(iframe);

    });

</script>
<div id="frame_reporte_general" style="width:100%;">
</div>